name: 'Code Coverage Reporter'
description: 'Adds and updates a comment on a pull request with code coverage info'
author: 'Casechek'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  github-token:
    description: 'Github token'
    required: true
  test-framework:
    description: 'Supports [karma|jest]'
    required: true
  passing-threshold:
    description: '% the coverage needs to be to pass the step, defaults to 80'
    required: false
  summary-path:
    description: 'Filepath to the coverage json file'
    required: false
  jest-test-command:
    description: 'Command to run Jest test coverage, defaults to "jest --coverage"'
    required: false
outputs:
  coverage:
    description: 'The test coverage report'
runs:
  using: 'node12'
  main: 'dist/index.js'



